# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'networkmain.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 585)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_set = QtWidgets.QWidget(self.centralwidget)
        self.widget_set.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_set.setObjectName("widget_set")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_set)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_net = QtWidgets.QComboBox(self.widget_set)
        self.comboBox_net.setObjectName("comboBox_net")
        self.comboBox_net.addItem("")
        self.comboBox_net.addItem("")
        self.comboBox_net.addItem("")
        self.comboBox_net.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_net)
        self.pushButton_test = QtWidgets.QPushButton(self.widget_set)
        self.pushButton_test.setObjectName("pushButton_test")
        self.verticalLayout_4.addWidget(self.pushButton_test)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_setting_server = QtWidgets.QWidget(self.widget_set)
        self.widget_setting_server.setObjectName("widget_setting_server")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_setting_server)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_ip = QtWidgets.QLabel(self.widget_setting_server)
        self.label_ip.setObjectName("label_ip")
        self.horizontalLayout_3.addWidget(self.label_ip)
        self.lineEdit_ip = QtWidgets.QLineEdit(self.widget_setting_server)
        self.lineEdit_ip.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_ip.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.horizontalLayout_3.addWidget(self.lineEdit_ip)
        self.label_port = QtWidgets.QLabel(self.widget_setting_server)
        self.label_port.setObjectName("label_port")
        self.horizontalLayout_3.addWidget(self.label_port)
        self.lineEdit_port = QtWidgets.QLineEdit(self.widget_setting_server)
        self.lineEdit_port.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.horizontalLayout_3.addWidget(self.lineEdit_port)
        self.checkBox_islocalport = QtWidgets.QCheckBox(self.widget_setting_server)
        self.checkBox_islocalport.setObjectName("checkBox_islocalport")
        self.horizontalLayout_3.addWidget(self.checkBox_islocalport)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_listen = QtWidgets.QPushButton(self.widget_setting_server)
        self.pushButton_listen.setObjectName("pushButton_listen")
        self.horizontalLayout_3.addWidget(self.pushButton_listen)
        self.verticalLayout_3.addWidget(self.widget_setting_server)
        self.widget_setting_client = QtWidgets.QWidget(self.widget_set)
        self.widget_setting_client.setObjectName("widget_setting_client")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_setting_client)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_optip = QtWidgets.QLabel(self.widget_setting_client)
        self.label_optip.setObjectName("label_optip")
        self.horizontalLayout_2.addWidget(self.label_optip)
        self.lineEdit_opip = QtWidgets.QLineEdit(self.widget_setting_client)
        self.lineEdit_opip.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_opip.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_opip.setObjectName("lineEdit_opip")
        self.horizontalLayout_2.addWidget(self.lineEdit_opip)
        self.label_opport = QtWidgets.QLabel(self.widget_setting_client)
        self.label_opport.setObjectName("label_opport")
        self.horizontalLayout_2.addWidget(self.label_opport)
        self.lineEdit_opport = QtWidgets.QLineEdit(self.widget_setting_client)
        self.lineEdit_opport.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_opport.setObjectName("lineEdit_opport")
        self.horizontalLayout_2.addWidget(self.lineEdit_opport)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_client = QtWidgets.QPushButton(self.widget_setting_client)
        self.pushButton_client.setObjectName("pushButton_client")
        self.horizontalLayout_2.addWidget(self.pushButton_client)
        self.verticalLayout_3.addWidget(self.widget_setting_client)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addWidget(self.widget_set)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_CurrentConnection = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_CurrentConnection.setMaximumSize(QtCore.QSize(260, 16777215))
        self.groupBox_CurrentConnection.setObjectName("groupBox_CurrentConnection")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_CurrentConnection)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_allselect = QtWidgets.QPushButton(self.groupBox_CurrentConnection)
        self.pushButton_allselect.setObjectName("pushButton_allselect")
        self.gridLayout_2.addWidget(self.pushButton_allselect, 0, 1, 1, 1)
        self.pushButton_disconn = QtWidgets.QPushButton(self.groupBox_CurrentConnection)
        self.pushButton_disconn.setObjectName("pushButton_disconn")
        self.gridLayout_2.addWidget(self.pushButton_disconn, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 2, 1, 1, 1)
        self.listWidget_clientlist = QtWidgets.QListWidget(self.groupBox_CurrentConnection)
        self.listWidget_clientlist.setObjectName("listWidget_clientlist")
        self.gridLayout_2.addWidget(self.listWidget_clientlist, 0, 0, 3, 1)
        self.horizontalLayout.addWidget(self.groupBox_CurrentConnection)
        self.groupBox_sendarea = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_sendarea.setMaximumSize(QtCore.QSize(420, 16777215))
        self.groupBox_sendarea.setObjectName("groupBox_sendarea")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_sendarea)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_ishex_send = QtWidgets.QCheckBox(self.groupBox_sendarea)
        self.checkBox_ishex_send.setObjectName("checkBox_ishex_send")
        self.gridLayout.addWidget(self.checkBox_ishex_send, 0, 0, 1, 1)
        self.checkBox_replysourcedata = QtWidgets.QCheckBox(self.groupBox_sendarea)
        self.checkBox_replysourcedata.setObjectName("checkBox_replysourcedata")
        self.gridLayout.addWidget(self.checkBox_replysourcedata, 0, 1, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 5, 1, 1)
        self.pushButton_clear_send = QtWidgets.QPushButton(self.groupBox_sendarea)
        self.pushButton_clear_send.setObjectName("pushButton_clear_send")
        self.gridLayout.addWidget(self.pushButton_clear_send, 0, 6, 1, 1)
        self.checkBox_auotsend = QtWidgets.QCheckBox(self.groupBox_sendarea)
        self.checkBox_auotsend.setObjectName("checkBox_auotsend")
        self.gridLayout.addWidget(self.checkBox_auotsend, 1, 0, 1, 2)
        self.label_interval = QtWidgets.QLabel(self.groupBox_sendarea)
        self.label_interval.setObjectName("label_interval")
        self.gridLayout.addWidget(self.label_interval, 1, 2, 1, 1)
        self.lineEdit_interval = QtWidgets.QLineEdit(self.groupBox_sendarea)
        self.lineEdit_interval.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_interval.setObjectName("lineEdit_interval")
        self.gridLayout.addWidget(self.lineEdit_interval, 1, 3, 1, 1)
        self.label_unit = QtWidgets.QLabel(self.groupBox_sendarea)
        self.label_unit.setObjectName("label_unit")
        self.gridLayout.addWidget(self.label_unit, 1, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 5, 1, 1)
        self.pushButton_send = QtWidgets.QPushButton(self.groupBox_sendarea)
        self.pushButton_send.setObjectName("pushButton_send")
        self.gridLayout.addWidget(self.pushButton_send, 1, 6, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.textEdit_send = QtWidgets.QTextEdit(self.groupBox_sendarea)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_send.setFont(font)
        self.textEdit_send.setObjectName("textEdit_send")
        self.verticalLayout_2.addWidget(self.textEdit_send)
        self.horizontalLayout.addWidget(self.groupBox_sendarea)
        self.groupBox_recvarea = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_recvarea.setObjectName("groupBox_recvarea")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_recvarea)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_ishex_recv = QtWidgets.QCheckBox(self.groupBox_recvarea)
        self.checkBox_ishex_recv.setObjectName("checkBox_ishex_recv")
        self.horizontalLayout_6.addWidget(self.checkBox_ishex_recv)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.pushButton_stopdisaply = QtWidgets.QPushButton(self.groupBox_recvarea)
        self.pushButton_stopdisaply.setObjectName("pushButton_stopdisaply")
        self.horizontalLayout_6.addWidget(self.pushButton_stopdisaply)
        self.pushButton_clear_recv = QtWidgets.QPushButton(self.groupBox_recvarea)
        self.pushButton_clear_recv.setObjectName("pushButton_clear_recv")
        self.horizontalLayout_6.addWidget(self.pushButton_clear_recv)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.textEdit_recv = QtWidgets.QTextEdit(self.groupBox_recvarea)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.textEdit_recv.setFont(font)
        self.textEdit_recv.setObjectName("textEdit_recv")
        self.verticalLayout.addWidget(self.textEdit_recv)
        self.horizontalLayout.addWidget(self.groupBox_recvarea)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_net.setItemText(0, _translate("MainWindow", "TCP服务端"))
        self.comboBox_net.setItemText(1, _translate("MainWindow", "TCP客户端"))
        self.comboBox_net.setItemText(2, _translate("MainWindow", "UDP服务端"))
        self.comboBox_net.setItemText(3, _translate("MainWindow", "UDP客户端"))
        self.pushButton_test.setText(_translate("MainWindow", "测试"))
        self.label_ip.setText(_translate("MainWindow", "本地IP:"))
        self.lineEdit_ip.setText(_translate("MainWindow", "127.0.0.1"))
        self.label_port.setText(_translate("MainWindow", "本地PORT:"))
        self.lineEdit_port.setText(_translate("MainWindow", "2500"))
        self.checkBox_islocalport.setText(_translate("MainWindow", "指定本地端口"))
        self.pushButton_listen.setText(_translate("MainWindow", "启动"))
        self.label_optip.setText(_translate("MainWindow", "目标IP:"))
        self.lineEdit_opip.setText(_translate("MainWindow", "127.0.0.1"))
        self.label_opport.setText(_translate("MainWindow", "目标PORT:"))
        self.lineEdit_opport.setText(_translate("MainWindow", "2500"))
        self.pushButton_client.setText(_translate("MainWindow", "连接"))
        self.groupBox_CurrentConnection.setTitle(_translate("MainWindow", "当前连接"))
        self.pushButton_allselect.setText(_translate("MainWindow", "全选"))
        self.pushButton_disconn.setText(_translate("MainWindow", "断开"))
        self.groupBox_sendarea.setTitle(_translate("MainWindow", "发送区域"))
        self.checkBox_ishex_send.setText(_translate("MainWindow", "16进制"))
        self.checkBox_replysourcedata.setText(_translate("MainWindow", "发送接收到的数据"))
        self.pushButton_clear_send.setText(_translate("MainWindow", "清除显示"))
        self.checkBox_auotsend.setText(_translate("MainWindow", "自动发送"))
        self.label_interval.setText(_translate("MainWindow", "间隔"))
        self.lineEdit_interval.setText(_translate("MainWindow", "500"))
        self.label_unit.setText(_translate("MainWindow", "ms"))
        self.pushButton_send.setText(_translate("MainWindow", "发送"))
        self.groupBox_recvarea.setTitle(_translate("MainWindow", "接收区域"))
        self.checkBox_ishex_recv.setText(_translate("MainWindow", "16进制"))
        self.pushButton_stopdisaply.setText(_translate("MainWindow", "暂停显示"))
        self.pushButton_clear_recv.setText(_translate("MainWindow", "清除显示"))

