# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'networkmain.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(637, 388)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.widget_set = QtGui.QWidget(self.centralwidget)
        self.widget_set.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_set.setObjectName(_fromUtf8("widget_set"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_set)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.comboBox_net = QtGui.QComboBox(self.widget_set)
        self.comboBox_net.setObjectName(_fromUtf8("comboBox_net"))
        self.comboBox_net.addItem(_fromUtf8(""))
        self.comboBox_net.addItem(_fromUtf8(""))
        self.comboBox_net.addItem(_fromUtf8(""))
        self.comboBox_net.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.comboBox_net)
        self.pushButton_test = QtGui.QPushButton(self.widget_set)
        self.pushButton_test.setObjectName(_fromUtf8("pushButton_test"))
        self.verticalLayout_4.addWidget(self.pushButton_test)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget_setting_server = QtGui.QWidget(self.widget_set)
        self.widget_setting_server.setObjectName(_fromUtf8("widget_setting_server"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_setting_server)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_ip = QtGui.QLabel(self.widget_setting_server)
        self.label_ip.setObjectName(_fromUtf8("label_ip"))
        self.horizontalLayout_3.addWidget(self.label_ip)
        self.lineEdit_ip = QtGui.QLineEdit(self.widget_setting_server)
        self.lineEdit_ip.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_ip.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_ip.setObjectName(_fromUtf8("lineEdit_ip"))
        self.horizontalLayout_3.addWidget(self.lineEdit_ip)
        self.label_port = QtGui.QLabel(self.widget_setting_server)
        self.label_port.setObjectName(_fromUtf8("label_port"))
        self.horizontalLayout_3.addWidget(self.label_port)
        self.lineEdit_port = QtGui.QLineEdit(self.widget_setting_server)
        self.lineEdit_port.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_port.setObjectName(_fromUtf8("lineEdit_port"))
        self.horizontalLayout_3.addWidget(self.lineEdit_port)
        self.checkBox_islocalport = QtGui.QCheckBox(self.widget_setting_server)
        self.checkBox_islocalport.setObjectName(_fromUtf8("checkBox_islocalport"))
        self.horizontalLayout_3.addWidget(self.checkBox_islocalport)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_listen = QtGui.QPushButton(self.widget_setting_server)
        self.pushButton_listen.setObjectName(_fromUtf8("pushButton_listen"))
        self.horizontalLayout_3.addWidget(self.pushButton_listen)
        self.verticalLayout_3.addWidget(self.widget_setting_server)
        self.widget_setting_client = QtGui.QWidget(self.widget_set)
        self.widget_setting_client.setObjectName(_fromUtf8("widget_setting_client"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_setting_client)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_optip = QtGui.QLabel(self.widget_setting_client)
        self.label_optip.setObjectName(_fromUtf8("label_optip"))
        self.horizontalLayout_2.addWidget(self.label_optip)
        self.lineEdit_objip = QtGui.QLineEdit(self.widget_setting_client)
        self.lineEdit_objip.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_objip.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEdit_objip.setObjectName(_fromUtf8("lineEdit_objip"))
        self.horizontalLayout_2.addWidget(self.lineEdit_objip)
        self.label_opport = QtGui.QLabel(self.widget_setting_client)
        self.label_opport.setObjectName(_fromUtf8("label_opport"))
        self.horizontalLayout_2.addWidget(self.label_opport)
        self.lineEdit_objport = QtGui.QLineEdit(self.widget_setting_client)
        self.lineEdit_objport.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_objport.setObjectName(_fromUtf8("lineEdit_objport"))
        self.horizontalLayout_2.addWidget(self.lineEdit_objport)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_client = QtGui.QPushButton(self.widget_setting_client)
        self.pushButton_client.setObjectName(_fromUtf8("pushButton_client"))
        self.horizontalLayout_2.addWidget(self.pushButton_client)
        self.verticalLayout_3.addWidget(self.widget_setting_client)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addWidget(self.widget_set)
        self.groupBox_sendarea = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_sendarea.setObjectName(_fromUtf8("groupBox_sendarea"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_sendarea)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBox_ishex_send = QtGui.QCheckBox(self.groupBox_sendarea)
        self.checkBox_ishex_send.setObjectName(_fromUtf8("checkBox_ishex_send"))
        self.horizontalLayout.addWidget(self.checkBox_ishex_send)
        self.checkBox_replysourcedata = QtGui.QCheckBox(self.groupBox_sendarea)
        self.checkBox_replysourcedata.setObjectName(_fromUtf8("checkBox_replysourcedata"))
        self.horizontalLayout.addWidget(self.checkBox_replysourcedata)
        self.checkBox_auotsend = QtGui.QCheckBox(self.groupBox_sendarea)
        self.checkBox_auotsend.setObjectName(_fromUtf8("checkBox_auotsend"))
        self.horizontalLayout.addWidget(self.checkBox_auotsend)
        self.label_interval = QtGui.QLabel(self.groupBox_sendarea)
        self.label_interval.setObjectName(_fromUtf8("label_interval"))
        self.horizontalLayout.addWidget(self.label_interval)
        self.lineEdit_interval = QtGui.QLineEdit(self.groupBox_sendarea)
        self.lineEdit_interval.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_interval.setObjectName(_fromUtf8("lineEdit_interval"))
        self.horizontalLayout.addWidget(self.lineEdit_interval)
        self.label_unit = QtGui.QLabel(self.groupBox_sendarea)
        self.label_unit.setObjectName(_fromUtf8("label_unit"))
        self.horizontalLayout.addWidget(self.label_unit)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton_clear_send = QtGui.QPushButton(self.groupBox_sendarea)
        self.pushButton_clear_send.setObjectName(_fromUtf8("pushButton_clear_send"))
        self.horizontalLayout.addWidget(self.pushButton_clear_send)
        self.pushButton_send = QtGui.QPushButton(self.groupBox_sendarea)
        self.pushButton_send.setObjectName(_fromUtf8("pushButton_send"))
        self.horizontalLayout.addWidget(self.pushButton_send)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit_send = QtGui.QTextEdit(self.groupBox_sendarea)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.textEdit_send.setFont(font)
        self.textEdit_send.setObjectName(_fromUtf8("textEdit_send"))
        self.verticalLayout.addWidget(self.textEdit_send)
        self.verticalLayout_5.addWidget(self.groupBox_sendarea)
        self.groupBox_recvarea = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_recvarea.setObjectName(_fromUtf8("groupBox_recvarea"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_recvarea)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkBox_ishex_recv = QtGui.QCheckBox(self.groupBox_recvarea)
        self.checkBox_ishex_recv.setObjectName(_fromUtf8("checkBox_ishex_recv"))
        self.horizontalLayout_6.addWidget(self.checkBox_ishex_recv)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.pushButton_stopdisaply = QtGui.QPushButton(self.groupBox_recvarea)
        self.pushButton_stopdisaply.setObjectName(_fromUtf8("pushButton_stopdisaply"))
        self.horizontalLayout_6.addWidget(self.pushButton_stopdisaply)
        self.pushButton_clear_recv = QtGui.QPushButton(self.groupBox_recvarea)
        self.pushButton_clear_recv.setObjectName(_fromUtf8("pushButton_clear_recv"))
        self.horizontalLayout_6.addWidget(self.pushButton_clear_recv)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.textEdit_recv = QtGui.QTextEdit(self.groupBox_recvarea)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        self.textEdit_recv.setFont(font)
        self.textEdit_recv.setObjectName(_fromUtf8("textEdit_recv"))
        self.verticalLayout_2.addWidget(self.textEdit_recv)
        self.verticalLayout_5.addWidget(self.groupBox_recvarea)
        spacerItem6 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.comboBox_net.setItemText(0, _translate("MainWindow", "TCP服务端", None))
        self.comboBox_net.setItemText(1, _translate("MainWindow", "TCP客户端", None))
        self.comboBox_net.setItemText(2, _translate("MainWindow", "UDP服务端", None))
        self.comboBox_net.setItemText(3, _translate("MainWindow", "UDP客户端", None))
        self.pushButton_test.setText(_translate("MainWindow", "测试", None))
        self.label_ip.setText(_translate("MainWindow", "本地IP:", None))
        self.lineEdit_ip.setText(_translate("MainWindow", "127.0.0.1", None))
        self.label_port.setText(_translate("MainWindow", "本地PORT:", None))
        self.lineEdit_port.setText(_translate("MainWindow", "2500", None))
        self.checkBox_islocalport.setText(_translate("MainWindow", "指定本地端口", None))
        self.pushButton_listen.setText(_translate("MainWindow", "启动", None))
        self.label_optip.setText(_translate("MainWindow", "目标IP:", None))
        self.lineEdit_objip.setText(_translate("MainWindow", "127.0.0.1", None))
        self.label_opport.setText(_translate("MainWindow", "目标PORT:", None))
        self.lineEdit_objport.setText(_translate("MainWindow", "2500", None))
        self.pushButton_client.setText(_translate("MainWindow", "连接", None))
        self.groupBox_sendarea.setTitle(_translate("MainWindow", "发送区域", None))
        self.checkBox_ishex_send.setText(_translate("MainWindow", "16进制", None))
        self.checkBox_replysourcedata.setText(_translate("MainWindow", "发送接收到的数据", None))
        self.checkBox_auotsend.setText(_translate("MainWindow", "自动发送", None))
        self.label_interval.setText(_translate("MainWindow", "间隔", None))
        self.lineEdit_interval.setText(_translate("MainWindow", "500", None))
        self.label_unit.setText(_translate("MainWindow", "ms", None))
        self.pushButton_clear_send.setText(_translate("MainWindow", "清除显示", None))
        self.pushButton_send.setText(_translate("MainWindow", "发送", None))
        self.groupBox_recvarea.setTitle(_translate("MainWindow", "接收区域", None))
        self.checkBox_ishex_recv.setText(_translate("MainWindow", "16进制", None))
        self.pushButton_stopdisaply.setText(_translate("MainWindow", "暂停显示", None))
        self.pushButton_clear_recv.setText(_translate("MainWindow", "清除显示", None))

